baseURL = "https://noiselab.live/"
languageCode = "en-us"
title = "NoiseLab"
theme = "hugo-goa"
author = "NoiseLab"

[params]
author = "#35c3 @ Arts & Play Assembly"
description = "Hausmusik is coming to Congress! The Noise Lab is an interactive session studio, which invites all Geeks and Geekettes to use our setup to experiment and make music. We’re offering a fully equipped open stage with serval synthesisers, stage piano, guitars and e-drums. For the surrounding audience the main mix is provided via headphones and audio streaming to mobile devices. We hope there will be some interaction with the maker community at Congress, which is also known to be good friends with synths and noise."
authorimage = "portrait.jpg"

[params.meta]
description = "Noise Laboratory at 35c3"
keywords = "noise, music, art, 35c3"

[[menu.main]]

[params.social]
twitter = "noiselab_live"

[params.extra]
copyright = "2018 copyleft"